import './globals.css'
import { Inter, Roboto } from 'next/font/google'
import Nav from '../Components/Auth/Nav'

const inter = Inter({ subsets: ['latin'], weight: ["400", "700"], variable: "--font-inter" })
const roboto = Roboto({ subsets: ['latin'], weight: ["400", "700"], variable: "--font-roboto" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={roboto.className}>
      <title>postIt!</title>
      <body className={` ${roboto.variable} bg-gray-200 `}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
